[package]
name = "ilo-lawa"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.28", default-features = false, features = ["alloc"] }
log = "0.4"
x86_64 = "0.14"
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.9"
virtio-drivers = { version = "0.7", default-features = false, features = ["alloc"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
